name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted
    container: ubuntu:22.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: ./src
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/jekyll-ci-image:latest
            ghcr.io/${{ github.repository_owner }}/jekyll-ci-image:${{ github.sha }}

      - name: Log out from GitHub Container Registry
        run: docker logout ghcr.io

      - name: Clean up old versions
        run: |
          # Get a list of all versions of the container image
          versions=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/orgs/${{ github.repository_owner }}/packages/container/jekyll-ci-image/versions" | jq -r '.[].id')

          # Keep the latest 5 versions and delete the rest
          count=0
          for version in $versions; do
            count=$((count + 1))
            if [ $count -gt 5 ]; then
              curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/orgs/${{ github.repository_owner }}/packages/container/jekyll-ci-image/versions/$version"
            fi
          done
